export const COMMON = {
  LOADING: 'LOADING',
  LOADING_END: 'LOADING_END',
  LOADING_USER: 'LOADING_USER',
  LOADING_USER_END: 'LOADING_USER_END',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export const PRODUCTS = {
  LOADING: 'PRODUCTS_LOADING',
  LOADING_END: 'PRODUCTS_LOADING_END',
  GET: 'PRODUCTS_GET',
  GET_FILTERED: 'PRODUCTS_GET_FILTERED'
};

export const CATEGORIES = {
  GET: 'CATEGORIES_GET'
};

export const ORDERS = {
  ADD_CART: 'ORDERS_ADD_CART',
  GET: 'ORDERS_GET',
  SET_CART: 'ORDERS_SET_CART'
};
