export const COMMON = {
  LOADING: 'LOADING',
  LOADING_END: 'LOADING_END',
  LOGIN: 'LOGIN'
};

export const PRODUCTS = {
  LOADING: 'PRODUCTS_LOADING',
  LOADING_END: 'PRODUCTS_LOADING_END',
  GET: 'PRODUCTS_GET'
};
